version: 0.0
os: linux
files:
  - source: /scripts
    destination: /home/ec2-user/scripts
    overwrite: true
  - source: /app
    destination: /home/ec2-user/app
    overwrite: true

permissions:
  - object: /home/ec2-user/logs
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /home/ec2-user/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /home/ec2-user/deploy
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /etc/redis
    pattern: "redis.conf"
    owner: redis
    group: redis
    mode: 644

hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user