spring:
  config:
    import: "aws-secretsmanager:/WorthyI/dev"
  security:
    oauth2:
      client:
        registration:
          apple:
            provider: apple
            client-id: ${APPLE_OAUTH2_KEY_ID}
            client-secret: ${APPLE_OAUTH2_SECRET}
            scope: name email
            redirect-uri: "https://api-dev.worthyilife.com/login/oauth2/code/{registrationId}"
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
            redirect-uri: "https://api-dev.worthyilife.com/login/oauth2/code/{registrationId}"
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-name-attribute: sub
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
logging:
  level:
    root: DEBUG