spring:
  config:
    import: optional:aws-secretsmanager:/WorthyI/dev
  cloud:
    aws:
      region:
        static: ap-northeast-2
  security:
    oauth2:
      client:
        registration:
          apple:
            client-id: ${APPLE_CLIENT_ID}
            client-secret: ${APPLE_CLIENT_SECRET}
            scope: openid, name, email
            redirect-uri: "https://api-dev.worthyilife.com/login/oauth2/code/{registrationId}"
            client-authentication-method: post
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: ${DEV_GOOGLE_CLIENT_ID}
            client-secret: ${DEV_GOOGLE_CLIENT_SECRET}
            scope: email, profile
        provider:
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token
            user-name-attribute: sub
            issuer-uri: https://appleid.apple.com
            jwk-set-uri: https://appleid.apple.com/auth/keys
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
logging:
  level:
    root: DEBUG

apple:
  url: https://appleid.apple.com