name: Deploy to EC2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download and install Java 23
      run: |
        wget https://corretto.aws/downloads/latest/amazon-corretto-23-x64-linux-jdk.tar.gz
        tar -xzf amazon-corretto-23-x64-linux-jdk.tar.gz
        sudo mv amazon-corretto-23.0.1.8.1-linux-x64 /usr/local/
        echo "JAVA_HOME=/usr/local/amazon-corretto-23.0.1.8.1-linux-x64" >> $GITHUB_ENV
        echo "/usr/local/amazon-corretto-23.0.1.8.1-linux-x64/bin" >> $GITHUB_PATH

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive artifacts
      run: zip -r build/libs/app.zip build/libs/*.jar

    - name: Configure AWS credentials for S3
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S3 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3 }}
        aws-region: ap-northeast-2
    
    - name: Upload to S3
      run: aws s3 cp build/libs/app.zip s3://worthyi-bucket/deploy/app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2 using CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name ${{ secrets.AWS_CODE_DEPLOY_APPLICATION }} \
          --deployment-group-name ${{ secrets.AWS_CODE_DEPLOY_GROUP }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --s3-location bucket=worthyi-bucket,bundleType=zip,key=deploy/app.zip