     name: Deploy to EC2

     on:
       push:
         branches:
           - develop

     jobs:
       build:
         runs-on: ubuntu-latest

         steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up JDK 23.0.1
           uses: actions/setup-java@v3
           with:
             distribution: 'corretto'
             java-version: '23.0.1'

         - name: Grant execute permission for Gradle
           run: chmod +x gradlew

         - name: Build with Gradle
           run: ./gradlew build

         - name: Upload artifact
           uses: actions/upload-artifact@v2
           with:
             name: app
             path: build/libs/*.jar

       deploy:
         runs-on: ubuntu-latest
         needs: build

         steps:
         - name: Download artifact
           uses: actions/download-artifact@v2
           with:
             name: app

         - name: Copy files via SSH
           uses: appleboy/scp-action@v0.1.1
           with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USER }}
             key: ${{ secrets.EC2_KEY }}
             source: "build/libs/*.jar"
             target: "/home/ec2-user/"

         - name: Execute remote command via SSH
           uses: appleboy/ssh-action@v0.1.1
           with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USER }}
             key: ${{ secrets.EC2_KEY }}
             script: |
               sudo yum update -y
               sudo amazon-linux-extras install java-openjdk11 -y
               java -jar /home/ec2-user/your-app.jar
