     name: Deploy to EC2

     on:
       push:
         branches:
           - develop

     jobs:
       build:
         runs-on: ubuntu-latest

         steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Download and install Java 23
           run: |
             wget https://corretto.aws/downloads/latest/amazon-corretto-23-x64-linux-jdk.tar.gz
             tar -xzf amazon-corretto-23-x64-linux-jdk.tar.gz
             sudo mv amazon-corretto-23.0.1.8.1-linux-x64 /usr/local/
             echo "JAVA_HOME=/usr/local/amazon-corretto-23.0.1.8.1-linux-x64" >> $GITHUB_ENV
             echo "/usr/local/amazon-corretto-23.0.1.8.1-linux-x64/bin" >> $GITHUB_PATH

         - name: Grant execute permission for Gradle
           run: chmod +x gradlew

         - name: Build with Gradle
           run: ./gradlew build

         - name: Upload artifact
           uses: actions/upload-artifact@v3
           with:
             name: app
             path: build/libs/*.jar

       deploy:
         runs-on: ubuntu-latest
         needs: build

         steps:
         - name: Download artifact
           uses: actions/download-artifact@v3
           with:
             name: app

         - name: Verify artifact exists
           run: ls -l plugin/build/libs/ || echo "No files found in plugin/build/libs/"

         - name: Copy files via SSH
           uses: appleboy/scp-action@v0.1.1
           with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USER }}
             key: ${{ secrets.EC2_KEY }}
             source: "plugin/build/libs/*.jar"
             target: "/home/ec2-user/"
             debug: true

         - name: Execute remote command via SSH
           uses: appleboy/ssh-action@v0.1.1
           with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USER }}
             key: ${{ secrets.EC2_KEY }}
             script: |
               sudo yum update -y
               wget https://corretto.aws/downloads/latest/amazon-corretto-23-x64-linux-jdk.tar.gz
               tar -xzf amazon-corretto-23-x64-linux-jdk.tar.gz
               sudo mv amazon-corretto-23.0.1.8.1-linux-x64 /usr/local/
               export JAVA_HOME=/usr/local/amazon-corretto-23.0.1.8.1-linux-x64
               export PATH=$JAVA_HOME/bin:$PATH
               java -jar /home/ec2-user/your-app.jar
